sudo: false

language: node_js
node_js:
  - 6
  - 8
  - 9

before_install:
  - npm install codecov.io coveralls
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script: npm run lint && npm run test:coverage
